[package]
name = "notion-day-one-migration"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3"
time = { version = "0.3", features = ["formatting", "parsing", "macros"] }
time-tz = { version = "2", features = ["system"] }
urlencoding = "2"
